# azure-pipelines.yml
trigger: none

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: desiredWorkItemTypes
    type: string
    default: "Bug,User Story,Task"
  - name: model
    type: string
    default: "gpt-4o"
  - name: modelBaseUrl
    type: string
    default: "https://api.openai.com/v1"
  - name: devopsBaseUrl
    type: string
    default: "https://dev.azure.com"
  - name: outputFolder
    type: string
    default: "Releases"
  - name: githubRepoUrl
    type: string
    default: "https://github.com/hankanman/Auto-Release-Notes.git"
  - name: githubTag
    type: string
    default: "main"
  - name: devOpsAPIVersion
    type: string
    default: "6.0"

variables:
  # The name of the DevOps organization.
  ORG_NAME: $(DevOps Organisation Name)
  # The name of the DevOps project.
  PROJECT_NAME: $(DevOps Project Name)
  # The name of the solution.
  SOLUTION_NAME: $(Solution Name)
  # The version of the release.
  RELEASE_VERSION: $(Release Version)
  # The query to retrieve the release information.
  RELEASE_QUERY: $(Release Query)
  # The API key for the GPT service (stored as a secret).
  MODEL_API_KEY: $(Model API Key)
  # A summary of the software.
  SOFTWARE_SUMMARY: $(Software Summary)
  # The GitHub tag or branch to generate release notes for.
  GITHUB_TAG: $(GitHub Tag)
  # The repository path to commit the release notes.
  COMMIT_REPO_PATH: $(Commit Repo Url)
  # The branch to commit the release notes to.
  COMMIT_BRANCH: $(Commit Branch)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      git clone --branch ${{parameters.githubTag}}  ${{parameters.githubRepoUrl}} script-repo
    displayName: "Clone GitHub Repository"

  - script: |
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)"  clone $(COMMIT_REPO_PATH) target-repo
    displayName: 'Clone Target Repository'

  - script: |
      cd script-repo
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
    displayName: "Set up Python environment"

  - script: |
      cd script-repo
      cat <<EOF > .env
      ORG_NAME=$DEVOPS_ORGANISATION_NAME
      PROJECT_NAME=$PROJECT_NAME
      SOLUTION_NAME=$SOLUTION_NAME
      RELEASE_VERSION=$RELEASE_VERSION
      RELEASE_QUERY=$RELEASE_QUERY
      GPT_API_KEY=$GPT_API_KEY
      PAT=$SYSTEM_ACCESSTOKEN
      MODEL=${{parameters.model}}
      MODEL_BASE_URL=${{parameters.modelBaseUrl}}
      DEVOPS_BASE_URL=${{parameters.devopsBaseUrl}}
      SOFTWARE_SUMMARY=$SOFTWARE_SUMMARY
      DESIRED_WORK_ITEM_TYPES=${{parameters.desiredWorkItemTypes}}
      OUTPUT_FOLDER=${{parameters.outputFolder}}
      DEVOPS_API_VERSION=${{parameters.devOpsAPIVersion}}
      EOF
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      GPT_API_KEY: $(Model API Key)
    displayName: 'Create .env file'

  - script: |
      cd script-repo
      source .venv/bin/activate
      python main.py
    displayName: "Run release notes script"


  - script: |
      mkdir -p "target-repo/${{parameters.outputFolder}}"
      cp -r "script-repo/${{parameters.outputFolder}}/"* "target-repo/${{parameters.outputFolder}}/"
      cd target-repo
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global user.name "$(Build.RequestedFor)"
      git checkout -b $(COMMIT_BRANCH) || git checkout $(COMMIT_BRANCH)
      git add "${{parameters.outputFolder}}/*"
      git commit -m "Add release notes for version $(RELEASE_VERSION)"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin $(COMMIT_BRANCH)
    displayName: 'Commit and push release notes'
